# database generated on 2024-04-16 20:54 GMT
!!omap
- /home/hammad/Temp-for-pmp-track/Tests/PMP-CFG-reg.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - pmp_cfg_locked_write_unrelated
- /home/hammad/Temp-for-pmp-track/Tests/PMP-CSR-access.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_access_permission
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-R-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_priority_r_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-R-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_priority_r
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-R.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_r
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-RW-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_priority_rw_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-RW-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_priority_rw
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-RW.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_rw
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-RWX.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_rwx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-RX-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_priority_rx_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-RX-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_priority_rx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-RX.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_rx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-X-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_priority_x_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-X-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_priority_x
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NA4-X.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NA4_x
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-R-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_priority_r_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-R-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_priority_r
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-R.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_r
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-RW-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_priority_rw_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-RW-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_priority_rw
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-RW.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_rw
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-RWX.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_rwx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-RX-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_priority_rx_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-RX-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_priority_rx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-RX.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_rx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-X-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_priority_x_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-X-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_priority_x
- /home/hammad/Temp-for-pmp-track/Tests/pmp-NAPOT-X.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_NAPOT_x
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-R-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_r_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-R-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_r
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-R.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_r
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-RW-priority-level-2..S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_rw_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-RW-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_rw
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-RW.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_rw
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-RWX-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_rwx_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-RWX.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_rwx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-RX-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_rx_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-RX-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_rx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-RX.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_rx
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-X-priority-level-2.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_x_level_2
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-X-priority.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_priority_x
- /home/hammad/Temp-for-pmp-track/Tests/pmp-TOR-X.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - PMP_TOR_x
